// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMS_BE.Models;

#nullable disable

namespace PIMS_BE.Migrations
{
    [DbContext(typeof(PimsDbContext))]
    [Migration("20260119090111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PIMS_BE.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double?>("MinScoreToPass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("AssessmentId")
                        .HasName("PK__Assessme__3D2BF81E9BCA0F4C");

                    b.HasIndex("ClassId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentCriterion", b =>
                {
                    b.Property<int>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriteriaId"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("CriteriaName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(10.0);

                    b.Property<double?>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.HasKey("CriteriaId")
                        .HasName("PK__Assessme__FE6ADBCDC69F72BC");

                    b.HasIndex("AssessmentId");

                    b.ToTable("AssessmentCriteria");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int?>("CouncilId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GradedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ScoreId")
                        .HasName("PK__Assessme__7DD229D1FB206AFF");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CouncilId");

                    b.HasIndex("GroupId");

                    b.HasIndex(new[] { "StudentId", "AssessmentId", "CouncilId" }, "UC_Student_Assessment")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL AND [AssessmentId] IS NOT NULL AND [CouncilId] IS NOT NULL");

                    b.ToTable("AssessmentScores");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Assessme__449EE125FD60ECF8");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("AssessmentSubmissions");
                });

            modelBuilder.Entity("PIMS_BE.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("GroupDeadline")
                        .HasColumnType("datetime");

                    b.Property<int?>("MaxGroupSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("MinGroupSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C0641262A6");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "ClassCode" }, "UQ__Classes__2ECD4A55A8E7D5AF")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PIMS_BE.Models.ClassStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__ClassSta__C8EE20632F4A82AE");

                    b.ToTable("ClassStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.ClassStudent", b =>
                {
                    b.Property<int>("ClassStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassStudentId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ClassStudentId")
                        .HasName("PK__ClassStu__B8147819E3D9DF8A");

                    b.HasIndex("ClassId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("PIMS_BE.Models.ClassStudentStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__ClassStu__C8EE2063330A2146");

                    b.ToTable("ClassStudentStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.Council", b =>
                {
                    b.Property<int>("CouncilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouncilId"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("CouncilName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DefenseDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Round")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("CouncilId")
                        .HasName("PK__Councils__1BBAA5C13C3157EC");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("StatusId");

                    b.ToTable("Councils");
                });

            modelBuilder.Entity("PIMS_BE.Models.CouncilStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__CouncilS__C8EE206374BAD9B5");

                    b.ToTable("CouncilStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.CriteriaGrade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int?>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GradedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("GraderId")
                        .HasColumnType("int");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId")
                        .HasName("PK__Criteria__54F87A57F45CBC05");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "GraderId", "StudentId", "CriteriaId" }, "UC_Grader_Student_Criteria")
                        .IsUnique()
                        .HasFilter("[GraderId] IS NOT NULL AND [StudentId] IS NOT NULL AND [CriteriaId] IS NOT NULL");

                    b.ToTable("CriteriaGrades");
                });

            modelBuilder.Entity("PIMS_BE.Models.DefenseSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("CouncilId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DefenseDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ScheduleId")
                        .HasName("PK__DefenseS__9C8A5B49B70F2DED");

                    b.HasIndex("CouncilId");

                    b.HasIndex("GroupId");

                    b.ToTable("DefenseSchedules");
                });

            modelBuilder.Entity("PIMS_BE.Models.Grader", b =>
                {
                    b.Property<int>("GraderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GraderId"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int?>("CouncilId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("GraderId")
                        .HasName("PK__Graders__9DDC5656C9FFCB1F");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CouncilId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Graders");
                });

            modelBuilder.Entity("PIMS_BE.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LeaderId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("GroupId")
                        .HasName("PK__Groups__149AF36AEAABF7A7");

                    b.HasIndex("ClassId");

                    b.HasIndex("LeaderId");

                    b.HasIndex("StatusId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GroupMemberId")
                        .HasName("PK__GroupMem__34481292E34BB5D6");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__GroupSta__C8EE2063B130FE64");

                    b.ToTable("GroupStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E125F828258");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PIMS_BE.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ProjectId")
                        .HasName("PK__Projects__761ABEF0F1049B07");

                    b.HasIndex("GroupId");

                    b.HasIndex("StatusId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PIMS_BE.Models.ProjectStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__ProjectS__C8EE20635FBCF8C4");

                    b.ToTable("ProjectStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07452472AF");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "IX_RefreshTokens_Token");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PIMS_BE.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A01D83829");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PIMS_BE.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__043301DD7BD5F7B2");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("PIMS_BE.Models.StudentCourseResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("CourseStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("FinalAverageScore")
                        .HasColumnType("float");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ResultId")
                        .HasName("PK__StudentC__97690208A2D6AD6D");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourseResults");
                });

            modelBuilder.Entity("PIMS_BE.Models.SubmissionFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("FileId")
                        .HasName("PK__Submissi__6F0F98BF9A4B5A58");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionFiles");
                });

            modelBuilder.Entity("PIMS_BE.Models.TeacherAssessment", b =>
                {
                    b.Property<int>("TeacherAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherAssessmentId"));

                    b.Property<DateTime?>("GradedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("GraderId")
                        .HasColumnType("int");

                    b.Property<double?>("RawScore")
                        .HasColumnType("float");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherAssessmentId")
                        .HasName("PK__TeacherA__CCB01FE9C22BF311");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "GraderId", "StudentId" }, "UC_Grader_Student")
                        .IsUnique()
                        .HasFilter("[GraderId] IS NOT NULL AND [StudentId] IS NOT NULL");

                    b.ToTable("TeacherAssessments");
                });

            modelBuilder.Entity("PIMS_BE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CF8712CB5");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534F7334DFE")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PIMS_BE.Models.UserStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__UserStat__C8EE2063AD1095E3");

                    b.ToTable("UserStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.Assessment", b =>
                {
                    b.HasOne("PIMS_BE.Models.Class", "Class")
                        .WithMany("Assessments")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Assessmen__Class__571DF1D5");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentCriterion", b =>
                {
                    b.HasOne("PIMS_BE.Models.Assessment", "Assessment")
                        .WithMany("AssessmentCriteria")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("FK__Assessmen__Asses__5CD6CB2B");

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentScore", b =>
                {
                    b.HasOne("PIMS_BE.Models.Assessment", "Assessment")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("FK__Assessmen__Asses__03F0984C");

                    b.HasOne("PIMS_BE.Models.Council", "Council")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("CouncilId")
                        .HasConstraintName("FK__Assessmen__Counc__06CD04F7");

                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__Assessmen__Group__05D8E0BE");

                    b.HasOne("PIMS_BE.Models.User", "Student")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Assessmen__Stude__04E4BC85");

                    b.Navigation("Assessment");

                    b.Navigation("Council");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentSubmission", b =>
                {
                    b.HasOne("PIMS_BE.Models.Assessment", "Assessment")
                        .WithMany("AssessmentSubmissions")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("FK__Assessmen__Asses__6C190EBB");

                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("AssessmentSubmissions")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__Assessmen__Group__6D0D32F4");

                    b.HasOne("PIMS_BE.Models.User", "UploadedByNavigation")
                        .WithMany("AssessmentSubmissions")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("FK__Assessmen__Uploa__6E01572D");

                    b.Navigation("Assessment");

                    b.Navigation("Group");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("PIMS_BE.Models.Class", b =>
                {
                    b.HasOne("PIMS_BE.Models.Semester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK__Classes__Semeste__3B75D760");

                    b.HasOne("PIMS_BE.Models.ClassStatus", "Status")
                        .WithMany("Classes")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__Classes__StatusI__3F466844");

                    b.HasOne("PIMS_BE.Models.User", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__Classes__Teacher__3C69FB99");

                    b.Navigation("Semester");

                    b.Navigation("Status");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PIMS_BE.Models.ClassStudent", b =>
                {
                    b.HasOne("PIMS_BE.Models.Class", "Class")
                        .WithMany("ClassStudents")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__ClassStud__Class__4316F928");

                    b.HasOne("PIMS_BE.Models.ClassStudentStatus", "Status")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__ClassStud__Statu__44FF419A");

                    b.HasOne("PIMS_BE.Models.User", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__ClassStud__Stude__440B1D61");

                    b.Navigation("Class");

                    b.Navigation("Status");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PIMS_BE.Models.Council", b =>
                {
                    b.HasOne("PIMS_BE.Models.Assessment", "Assessment")
                        .WithMany("Councils")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("FK__Councils__Assess__619B8048");

                    b.HasOne("PIMS_BE.Models.CouncilStatus", "Status")
                        .WithMany("Councils")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__Councils__Status__6383C8BA");

                    b.Navigation("Assessment");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PIMS_BE.Models.CriteriaGrade", b =>
                {
                    b.HasOne("PIMS_BE.Models.AssessmentCriterion", "Criteria")
                        .WithMany("CriteriaGrades")
                        .HasForeignKey("CriteriaId")
                        .HasConstraintName("FK__CriteriaG__Crite__7E37BEF6");

                    b.HasOne("PIMS_BE.Models.Grader", "Grader")
                        .WithMany("CriteriaGrades")
                        .HasForeignKey("GraderId")
                        .HasConstraintName("FK__CriteriaG__Grade__7C4F7684");

                    b.HasOne("PIMS_BE.Models.User", "Student")
                        .WithMany("CriteriaGrades")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__CriteriaG__Stude__7D439ABD");

                    b.Navigation("Criteria");

                    b.Navigation("Grader");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PIMS_BE.Models.DefenseSchedule", b =>
                {
                    b.HasOne("PIMS_BE.Models.Council", "Council")
                        .WithMany("DefenseSchedules")
                        .HasForeignKey("CouncilId")
                        .HasConstraintName("FK__DefenseSc__Counc__2739D489");

                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("DefenseSchedules")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__DefenseSc__Group__282DF8C2");

                    b.Navigation("Council");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PIMS_BE.Models.Grader", b =>
                {
                    b.HasOne("PIMS_BE.Models.Assessment", "Assessment")
                        .WithMany("Graders")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("FK__Graders__Assessm__6754599E");

                    b.HasOne("PIMS_BE.Models.Council", "Council")
                        .WithMany("Graders")
                        .HasForeignKey("CouncilId")
                        .HasConstraintName("FK__Graders__Council__693CA210");

                    b.HasOne("PIMS_BE.Models.User", "Teacher")
                        .WithMany("Graders")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__Graders__Teacher__68487DD7");

                    b.Navigation("Assessment");

                    b.Navigation("Council");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PIMS_BE.Models.Group", b =>
                {
                    b.HasOne("PIMS_BE.Models.Class", "Class")
                        .WithMany("Groups")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Groups__ClassId__47DBAE45");

                    b.HasOne("PIMS_BE.Models.User", "Leader")
                        .WithMany("Groups")
                        .HasForeignKey("LeaderId")
                        .HasConstraintName("FK__Groups__LeaderId__48CFD27E");

                    b.HasOne("PIMS_BE.Models.GroupStatus", "Status")
                        .WithMany("Groups")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__Groups__StatusId__49C3F6B7");

                    b.Navigation("Class");

                    b.Navigation("Leader");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupMember", b =>
                {
                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__GroupMemb__Group__4D94879B");

                    b.HasOne("PIMS_BE.Models.User", "Student")
                        .WithMany("GroupMembers")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__GroupMemb__Stude__4E88ABD4");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PIMS_BE.Models.Notification", b =>
                {
                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__0F624AF8");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.Project", b =>
                {
                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK__Projects__GroupI__52593CB8");

                    b.HasOne("PIMS_BE.Models.ProjectStatus", "Status")
                        .WithMany("Projects")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__Projects__Status__534D60F1");

                    b.Navigation("Group");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PIMS_BE.Models.RefreshToken", b =>
                {
                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__RefreshTo__UserI__2180FB33");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.StudentCourseResult", b =>
                {
                    b.HasOne("PIMS_BE.Models.Class", "Class")
                        .WithMany("StudentCourseResults")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__StudentCo__Class__0B91BA14");

                    b.HasOne("PIMS_BE.Models.User", "Student")
                        .WithMany("StudentCourseResults")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__StudentCo__Stude__0A9D95DB");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PIMS_BE.Models.SubmissionFile", b =>
                {
                    b.HasOne("PIMS_BE.Models.AssessmentSubmission", "Submission")
                        .WithMany("SubmissionFiles")
                        .HasForeignKey("SubmissionId")
                        .HasConstraintName("FK__Submissio__Submi__71D1E811");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("PIMS_BE.Models.TeacherAssessment", b =>
                {
                    b.HasOne("PIMS_BE.Models.Grader", "Grader")
                        .WithMany("TeacherAssessments")
                        .HasForeignKey("GraderId")
                        .HasConstraintName("FK__TeacherAs__Grade__76969D2E");

                    b.HasOne("PIMS_BE.Models.User", "Student")
                        .WithMany("TeacherAssessments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__TeacherAs__Stude__778AC167");

                    b.Navigation("Grader");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PIMS_BE.Models.User", b =>
                {
                    b.HasOne("PIMS_BE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleId__35BCFE0A");

                    b.HasOne("PIMS_BE.Models.UserStatus", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__Users__StatusId__36B12243");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PIMS_BE.Models.Assessment", b =>
                {
                    b.Navigation("AssessmentCriteria");

                    b.Navigation("AssessmentScores");

                    b.Navigation("AssessmentSubmissions");

                    b.Navigation("Councils");

                    b.Navigation("Graders");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentCriterion", b =>
                {
                    b.Navigation("CriteriaGrades");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentSubmission", b =>
                {
                    b.Navigation("SubmissionFiles");
                });

            modelBuilder.Entity("PIMS_BE.Models.Class", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("ClassStudents");

                    b.Navigation("Groups");

                    b.Navigation("StudentCourseResults");
                });

            modelBuilder.Entity("PIMS_BE.Models.ClassStatus", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("PIMS_BE.Models.ClassStudentStatus", b =>
                {
                    b.Navigation("ClassStudents");
                });

            modelBuilder.Entity("PIMS_BE.Models.Council", b =>
                {
                    b.Navigation("AssessmentScores");

                    b.Navigation("DefenseSchedules");

                    b.Navigation("Graders");
                });

            modelBuilder.Entity("PIMS_BE.Models.CouncilStatus", b =>
                {
                    b.Navigation("Councils");
                });

            modelBuilder.Entity("PIMS_BE.Models.Grader", b =>
                {
                    b.Navigation("CriteriaGrades");

                    b.Navigation("TeacherAssessments");
                });

            modelBuilder.Entity("PIMS_BE.Models.Group", b =>
                {
                    b.Navigation("AssessmentScores");

                    b.Navigation("AssessmentSubmissions");

                    b.Navigation("DefenseSchedules");

                    b.Navigation("GroupMembers");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupStatus", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("PIMS_BE.Models.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PIMS_BE.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PIMS_BE.Models.Semester", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("PIMS_BE.Models.User", b =>
                {
                    b.Navigation("AssessmentScores");

                    b.Navigation("AssessmentSubmissions");

                    b.Navigation("ClassStudents");

                    b.Navigation("Classes");

                    b.Navigation("CriteriaGrades");

                    b.Navigation("Graders");

                    b.Navigation("GroupMembers");

                    b.Navigation("Groups");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StudentCourseResults");

                    b.Navigation("TeacherAssessments");
                });

            modelBuilder.Entity("PIMS_BE.Models.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
