// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMS_BE.Models;

#nullable disable

namespace PIMS_BE.Migrations
{
    [DbContext(typeof(PimsDbContext))]
    [Migration("20260125053737_AddProjectSubmissionTable")]
    partial class AddProjectSubmissionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PIMS_BE.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("AssessmentId")
                        .HasName("PK__Assessme__3D2BF81E93898FB3");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "SemesterId", "Title" }, "UQ_Assessment_Semester")
                        .IsUnique()
                        .HasFilter("[Title] IS NOT NULL");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentCriterion", b =>
                {
                    b.Property<int>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriteriaId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("CriteriaName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("CriteriaId")
                        .HasName("PK__Assessme__FE6ADBCD67D1F7A9");

                    b.HasIndex(new[] { "AssessmentId", "CriteriaName" }, "UQ_Assessment_Criteria")
                        .IsUnique()
                        .HasFilter("[CriteriaName] IS NOT NULL");

                    b.ToTable("AssessmentCriteria");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ScoreId")
                        .HasName("PK__Assessme__7DD229D109426F44");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AssessmentId", "UserId" }, "UQ_Assessment_User")
                        .IsUnique();

                    b.ToTable("AssessmentScores");
                });

            modelBuilder.Entity("PIMS_BE.Models.Council", b =>
                {
                    b.Property<int>("CouncilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouncilId"));

                    b.Property<string>("CouncilName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("CouncilId")
                        .HasName("PK__Councils__1BBAA5C1103DE038");

                    b.HasIndex("SemesterId");

                    b.ToTable("Councils");
                });

            modelBuilder.Entity("PIMS_BE.Models.CouncilCriteriaGrade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("CouncilId")
                        .HasColumnType("int");

                    b.Property<int>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GradeId")
                        .HasName("PK__CouncilC__54F87A57D01930EF");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CouncilId", "GroupId", "UserId", "TeacherId", "CriteriaId" }, "UQ_Council_Grade")
                        .IsUnique();

                    b.ToTable("CouncilCriteriaGrades");
                });

            modelBuilder.Entity("PIMS_BE.Models.CouncilMember", b =>
                {
                    b.Property<int>("CouncilMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouncilMemberId"));

                    b.Property<int>("CouncilId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CouncilMemberId")
                        .HasName("PK__CouncilM__457943C1587454EE");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CouncilId", "UserId" }, "UQ_Council_Teacher")
                        .IsUnique();

                    b.ToTable("CouncilMembers");
                });

            modelBuilder.Entity("PIMS_BE.Models.CriteriaGrade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GradeId")
                        .HasName("PK__Criteria__54F87A57DD35BE02");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "CriteriaId" }, "IX_CriteriaGrades_Criteria");

                    b.HasIndex(new[] { "UserId", "CriteriaId" }, "UQ_Mentor_Grade")
                        .IsUnique();

                    b.ToTable("CriteriaGrades");
                });

            modelBuilder.Entity("PIMS_BE.Models.DefenseSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CouncilId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DefenseDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING");

                    b.HasKey("ScheduleId")
                        .HasName("PK__DefenseS__9C8A5B498CA6E544");

                    b.HasIndex(new[] { "CouncilId" }, "IX_Defense_Council");

                    b.HasIndex(new[] { "GroupId" }, "IX_Defense_Group");

                    b.HasIndex(new[] { "CouncilId", "GroupId" }, "UQ_Council_Group")
                        .IsUnique();

                    b.ToTable("DefenseSchedules");
                });

            modelBuilder.Entity("PIMS_BE.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LeaderId")
                        .HasColumnType("int");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("GroupId")
                        .HasName("PK__Groups__149AF36A64CFC685");

                    b.HasIndex("LeaderId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "MentorId" }, "IX_Groups_Mentor");

                    b.HasIndex(new[] { "SemesterId" }, "IX_Groups_Semester");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GroupMemberId")
                        .HasName("PK__GroupMem__34481292A74CFE56");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "GroupId" }, "IX_GroupMembers_Group");

                    b.HasIndex(new[] { "UserId" }, "IX_GroupMembers_User");

                    b.HasIndex(new[] { "UserId", "GroupId" }, "UQ_User_OneGroup")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupMemberStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__GroupMem__C8EE2063448AE27D");

                    b.ToTable("GroupMemberStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__GroupSta__C8EE2063AD734449");

                    b.ToTable("GroupStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.MentorRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TeacherComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestId")
                        .HasName("PK__MentorRe__33A8517A6B16E524");

                    b.HasIndex("GroupId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("MentorRequests");
                });

            modelBuilder.Entity("PIMS_BE.Models.MentorRequestStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__MentorRe__C8EE20632E620E5C");

                    b.ToTable("MentorRequestStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12B4D369AB");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PIMS_BE.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProjectId")
                        .HasName("PK__Projects__761ABEF0B7262053");

                    b.HasIndex("GroupId");

                    b.HasIndex("StatusId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PIMS_BE.Models.ProjectStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__ProjectS__C8EE20635A673F2B");

                    b.ToTable("ProjectStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.ProjectSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileResourceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReportUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SubmitterId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId")
                        .HasName("PK__ProjectS__449EE125918F1902");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectSubmissions");
                });

            modelBuilder.Entity("PIMS_BE.Models.ProjectTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FileResourceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TemplateUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateId")
                        .HasName("PK__ProjectT__F87ADD2755CD81C4");

                    b.HasIndex("SemesterId");

                    b.ToTable("ProjectTemplates");
                });

            modelBuilder.Entity("PIMS_BE.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AE514E27E");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PIMS_BE.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxGroupSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int?>("MinGroupSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SemesterName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__043301DD5B5ECBFD");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("PIMS_BE.Models.StudentFinalResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Grade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool?>("IsFinalized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResultId")
                        .HasName("PK__StudentF__97690208F0E399E9");

                    b.HasIndex("SemesterId");

                    b.HasIndex(new[] { "UserId", "SemesterId" }, "UQ_User_Semester")
                        .IsUnique();

                    b.ToTable("StudentFinalResults");
                });

            modelBuilder.Entity("PIMS_BE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C439FDF80");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "StatusId" }, "IX_Users_Status");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534E946C283")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PIMS_BE.Models.UserStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId")
                        .HasName("PK__UserStat__C8EE2063D5474FE5");

                    b.ToTable("UserStatus", (string)null);
                });

            modelBuilder.Entity("PIMS_BE.Models.Assessment", b =>
                {
                    b.HasOne("PIMS_BE.Models.User", "CreatedByNavigation")
                        .WithMany("Assessments")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Assessment_Creator");

                    b.HasOne("PIMS_BE.Models.Semester", "Semester")
                        .WithMany("Assessments")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_Assessment_Semester");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentCriterion", b =>
                {
                    b.HasOne("PIMS_BE.Models.Assessment", "Assessment")
                        .WithMany("AssessmentCriteria")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_AC_Assessment");

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentScore", b =>
                {
                    b.HasOne("PIMS_BE.Models.Assessment", "Assessment")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_AS_Assessment");

                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AS_User");

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.Council", b =>
                {
                    b.HasOne("PIMS_BE.Models.Semester", "Semester")
                        .WithMany("Councils")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_Council_Semester");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("PIMS_BE.Models.CouncilCriteriaGrade", b =>
                {
                    b.HasOne("PIMS_BE.Models.Council", "Council")
                        .WithMany("CouncilCriteriaGrades")
                        .HasForeignKey("CouncilId")
                        .IsRequired()
                        .HasConstraintName("FK_CCG_Council");

                    b.HasOne("PIMS_BE.Models.AssessmentCriterion", "Criteria")
                        .WithMany("CouncilCriteriaGrades")
                        .HasForeignKey("CriteriaId")
                        .IsRequired()
                        .HasConstraintName("FK_CCG_Criteria");

                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("CouncilCriteriaGrades")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_CCG_Group");

                    b.HasOne("PIMS_BE.Models.User", "Teacher")
                        .WithMany("CouncilCriteriaGradeTeachers")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_CCG_Teacher");

                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("CouncilCriteriaGradeUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CCG_User");

                    b.Navigation("Council");

                    b.Navigation("Criteria");

                    b.Navigation("Group");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.CouncilMember", b =>
                {
                    b.HasOne("PIMS_BE.Models.Council", "Council")
                        .WithMany("CouncilMembers")
                        .HasForeignKey("CouncilId")
                        .IsRequired()
                        .HasConstraintName("FK_CM_Council");

                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("CouncilMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CM_User");

                    b.Navigation("Council");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.CriteriaGrade", b =>
                {
                    b.HasOne("PIMS_BE.Models.AssessmentCriterion", "Criteria")
                        .WithMany("CriteriaGrades")
                        .HasForeignKey("CriteriaId")
                        .IsRequired()
                        .HasConstraintName("FK_CG_Criteria");

                    b.HasOne("PIMS_BE.Models.User", "Teacher")
                        .WithMany("CriteriaGradeTeachers")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_CG_Teacher");

                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("CriteriaGradeUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CG_User");

                    b.Navigation("Criteria");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.DefenseSchedule", b =>
                {
                    b.HasOne("PIMS_BE.Models.Council", "Council")
                        .WithMany("DefenseSchedules")
                        .HasForeignKey("CouncilId")
                        .IsRequired()
                        .HasConstraintName("FK_DS_Council");

                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("DefenseSchedules")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_DS_Group");

                    b.Navigation("Council");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PIMS_BE.Models.Group", b =>
                {
                    b.HasOne("PIMS_BE.Models.User", "Leader")
                        .WithMany("GroupLeaders")
                        .HasForeignKey("LeaderId")
                        .IsRequired()
                        .HasConstraintName("FK_Groups_Leader");

                    b.HasOne("PIMS_BE.Models.User", "Mentor")
                        .WithMany("GroupMentors")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("FK_Groups_Mentor");

                    b.HasOne("PIMS_BE.Models.Semester", "Semester")
                        .WithMany("Groups")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_Groups_Semester");

                    b.HasOne("PIMS_BE.Models.GroupStatus", "Status")
                        .WithMany("Groups")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Groups_Status");

                    b.Navigation("Leader");

                    b.Navigation("Mentor");

                    b.Navigation("Semester");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupMember", b =>
                {
                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GM_Group");

                    b.HasOne("PIMS_BE.Models.GroupMemberStatus", "Status")
                        .WithMany("GroupMembers")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_GM_Status");

                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_GM_User");

                    b.Navigation("Group");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.MentorRequest", b =>
                {
                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("MentorRequests")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_MR_Group");

                    b.HasOne("PIMS_BE.Models.MentorRequestStatus", "Status")
                        .WithMany("MentorRequests")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_MR_Status");

                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("MentorRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_MR_User");

                    b.Navigation("Group");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.Notification", b =>
                {
                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Noti_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.Project", b =>
                {
                    b.HasOne("PIMS_BE.Models.Group", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Projects_Group");

                    b.HasOne("PIMS_BE.Models.ProjectStatus", "Status")
                        .WithMany("Projects")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Projects_Status");

                    b.Navigation("Group");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PIMS_BE.Models.ProjectSubmission", b =>
                {
                    b.HasOne("PIMS_BE.Models.Project", "Project")
                        .WithMany("ProjectSubmissions")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Submission_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PIMS_BE.Models.ProjectTemplate", b =>
                {
                    b.HasOne("PIMS_BE.Models.Semester", "Semester")
                        .WithMany("ProjectTemplates")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_Template_Semester");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("PIMS_BE.Models.StudentFinalResult", b =>
                {
                    b.HasOne("PIMS_BE.Models.Semester", "Semester")
                        .WithMany("StudentFinalResults")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_SFR_Semester");

                    b.HasOne("PIMS_BE.Models.User", "User")
                        .WithMany("StudentFinalResults")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_SFR_User");

                    b.Navigation("Semester");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIMS_BE.Models.User", b =>
                {
                    b.HasOne("PIMS_BE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Role");

                    b.HasOne("PIMS_BE.Models.UserStatus", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Status");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PIMS_BE.Models.Assessment", b =>
                {
                    b.Navigation("AssessmentCriteria");

                    b.Navigation("AssessmentScores");
                });

            modelBuilder.Entity("PIMS_BE.Models.AssessmentCriterion", b =>
                {
                    b.Navigation("CouncilCriteriaGrades");

                    b.Navigation("CriteriaGrades");
                });

            modelBuilder.Entity("PIMS_BE.Models.Council", b =>
                {
                    b.Navigation("CouncilCriteriaGrades");

                    b.Navigation("CouncilMembers");

                    b.Navigation("DefenseSchedules");
                });

            modelBuilder.Entity("PIMS_BE.Models.Group", b =>
                {
                    b.Navigation("CouncilCriteriaGrades");

                    b.Navigation("DefenseSchedules");

                    b.Navigation("GroupMembers");

                    b.Navigation("MentorRequests");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupMemberStatus", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("PIMS_BE.Models.GroupStatus", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("PIMS_BE.Models.MentorRequestStatus", b =>
                {
                    b.Navigation("MentorRequests");
                });

            modelBuilder.Entity("PIMS_BE.Models.Project", b =>
                {
                    b.Navigation("ProjectSubmissions");
                });

            modelBuilder.Entity("PIMS_BE.Models.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PIMS_BE.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PIMS_BE.Models.Semester", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Councils");

                    b.Navigation("Groups");

                    b.Navigation("ProjectTemplates");

                    b.Navigation("StudentFinalResults");
                });

            modelBuilder.Entity("PIMS_BE.Models.User", b =>
                {
                    b.Navigation("AssessmentScores");

                    b.Navigation("Assessments");

                    b.Navigation("CouncilCriteriaGradeTeachers");

                    b.Navigation("CouncilCriteriaGradeUsers");

                    b.Navigation("CouncilMembers");

                    b.Navigation("CriteriaGradeTeachers");

                    b.Navigation("CriteriaGradeUsers");

                    b.Navigation("GroupLeaders");

                    b.Navigation("GroupMembers");

                    b.Navigation("GroupMentors");

                    b.Navigation("MentorRequests");

                    b.Navigation("Notifications");

                    b.Navigation("StudentFinalResults");
                });

            modelBuilder.Entity("PIMS_BE.Models.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
